# Generated by Django 3.2.9 on 2021-11-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=200, verbose_name='Events Title')),
                ('events_image', models.ImageField(upload_to='events_picture', verbose_name='Image')),
                ('events_date', models.DateTimeField(auto_now_add=True)),
                ('events_details', models.TextField(verbose_name='what is on your mind?')),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('events_image_caption', models.TextField(verbose_name='Image caption')),
            ],
        ),
    ]
